name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2  # Mise à jour de v1 à v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Mise à jour de v1 à v2

      - name: Check Docker version
        run: docker --version

      # Connexion à Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2  # Mise à jour de v1 à v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Connexion à GitHub Container Registry (GHCR)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2  # Mise à jour de v3 à v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Construction et push de l'image Docker
      - name: Build and push
        uses: docker/build-push-action@v3  # Mise à jour de v2 à v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/animal-farm-nodejs:latest
            ghcr.io/bellaajsolaima/animal-farm-nodejs:latest

